name: build_and_test

run-name: Build and Test

on:
  push:
    branches:
      - "**"

jobs:
  build_and_test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Build and Push
        uses: docker/build-push-action@v6.18.0
        with:
          tags: test_docker_alias:local
          load: true

      - name: Start
        run: ./start.sh

      - name: Test
        run: ./test.sh

      - name: Stop
        if: ${{ always() }}
        run: ./stop.sh
